#  Copyright 2018 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


steps:
- name: 'gcr.io/cloud-builders/npm'
  id: npm-install
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  id: npm-build
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: appengine-deploy
  waitFor:
  - npm-build
  entrypoint: gcloud
  dir: /workspace/dist
  args: 
  - app 
  - deploy
- name: 'gcr.io/kaniko-project/executor:latest'
  id: container-build
  waitFor:
  - npm-build
  args: 
  - --dockerfile=app/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/ai-agent-scaffold
  - --context=dir:///workspace/dist
  - --cache=true
  - --cache-ttl=168h
  timeout: 1200s
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: cloudrun-deploy
  waitFor:
  - container-build
  entrypoint: gcloud
  args: 
  - run 
  - deploy
  - ai-agent-scaffold-webapp
  - --image=gcr.io/$PROJECT_ID/ai-agent-scaffold
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
  - --ingress=all
  - --memory=2Gi
  - --no-use-http2
timeout: 1800s